-- ============================================================
-- ARGUS · Revenue Intelligence
-- Contratos oficiais do módulo Faturamento
-- ============================================================

create table if not exists public.mart_revenue_monthly (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,
    mes integer not null,
    mes_nome text,
    ano_mes text not null,
    trimestre integer,
    semestre integer,

    empresa text not null default 'TOTAL',
    nivel text not null default 'geral',

    faturamento numeric(18, 2) not null default 0,
    pedidos integer not null default 0,
    ticket_medio numeric(18, 2) not null default 0,
    empresas_ativas integer not null default 0,
    vendedores_ativos integer not null default 0,

    tem_movimento boolean not null default false,
    periodo_futuro boolean not null default false,
    mes_em_aberto boolean not null default false,

    faturamento_mes_anterior numeric(18, 2),
    crescimento_mom numeric(18, 6),
    faturamento_ano_anterior numeric(18, 2),
    crescimento_yoy numeric(18, 6),
    acumulado_ytd numeric(18, 2),

    meta numeric(18, 2),
    supermeta numeric(18, 2),
    hipermeta numeric(18, 2),

    status_meta text,
    meta_valida boolean not null default false,

    atingimento_meta numeric(18, 6),
    atingimento_supermeta numeric(18, 6),
    atingimento_hipermeta numeric(18, 6),

    gap_meta numeric(18, 2),
    gap_supermeta numeric(18, 2),
    gap_hipermeta numeric(18, 2),

    falta_para_meta numeric(18, 2),
    falta_para_supermeta numeric(18, 2),
    falta_para_hipermeta numeric(18, 2),

    faixa_desempenho text,

    empresas_com_meta integer,
    vendedores_cadastrados_meta integer,
    vendedores_com_meta integer,
    vendedores_pendentes integer,

    created_at timestamptz not null default now(),

    unique (reference_date, ano, mes, empresa, nivel)
);


create table if not exists public.mart_revenue_company_monthly (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,
    mes integer not null,
    ano_mes text not null,

    empresa text not null,
    nivel text not null default 'empresa',

    faturamento numeric(18, 2) not null default 0,
    pedidos integer not null default 0,
    vendedores_ativos integer not null default 0,
    ticket_medio numeric(18, 2) not null default 0,

    faturamento_total_mes numeric(18, 2) not null default 0,
    participacao_mensal numeric(18, 6) not null default 0,
    ranking_empresa_mes integer,

    meta numeric(18, 2),
    supermeta numeric(18, 2),
    hipermeta numeric(18, 2),

    status_meta text,
    meta_valida boolean not null default false,

    atingimento_meta numeric(18, 6),
    atingimento_supermeta numeric(18, 6),
    atingimento_hipermeta numeric(18, 6),

    gap_meta numeric(18, 2),
    gap_supermeta numeric(18, 2),
    gap_hipermeta numeric(18, 2),

    falta_para_meta numeric(18, 2),
    falta_para_supermeta numeric(18, 2),
    falta_para_hipermeta numeric(18, 2),

    faixa_desempenho text,

    vendedores_cadastrados_meta integer,
    vendedores_com_meta integer,
    vendedores_pendentes integer,

    created_at timestamptz not null default now(),

    unique (reference_date, ano, mes, empresa)
);


create table if not exists public.mart_revenue_seller_monthly (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,
    mes integer not null,
    ano_mes text not null,

    empresa text not null,
    vendedor_key text not null,
    vendedor text not null,
    seller_identity text not null,

    nivel text not null default 'vendedor',

    faturamento numeric(18, 2) not null default 0,
    pedidos integer not null default 0,
    ticket_medio numeric(18, 2) not null default 0,

    faturamento_empresa_mes numeric(18, 2) not null default 0,
    participacao_empresa numeric(18, 6) not null default 0,

    ranking_vendedor_empresa integer,
    ranking_faturamento_empresa integer,
    ranking_atingimento_empresa numeric,

    meta numeric(18, 2),
    supermeta numeric(18, 2),
    hipermeta numeric(18, 2),

    status_meta text,
    meta_valida boolean not null default false,
    meta_configurada boolean,
    meta_pendente boolean,

    atingimento_meta numeric(18, 6),
    atingimento_supermeta numeric(18, 6),
    atingimento_hipermeta numeric(18, 6),

    gap_meta numeric(18, 2),
    gap_supermeta numeric(18, 2),
    gap_hipermeta numeric(18, 2),

    falta_para_meta numeric(18, 2),
    falta_para_supermeta numeric(18, 2),
    falta_para_hipermeta numeric(18, 2),

    faixa_desempenho text,

    created_at timestamptz not null default now(),

    unique (
        reference_date,
        ano,
        mes,
        empresa,
        vendedor_key
    )
);


create table if not exists public.mart_revenue_current_summary (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,
    mes integer not null,

    faturamento numeric(18, 2) not null default 0,

    meta numeric(18, 2),
    supermeta numeric(18, 2),
    hipermeta numeric(18, 2),

    atingimento_meta numeric(18, 6),
    gap_meta numeric(18, 2),

    status_meta text,
    faixa_desempenho text,

    empresas_com_faturamento integer not null default 0,
    vendedores_com_faturamento integer not null default 0,
    vendedores_com_meta_valida integer not null default 0,
    vendedores_que_bateram_meta integer not null default 0,
    vendedores_em_supermeta integer not null default 0,
    vendedores_em_hipermeta integer not null default 0,

    status text not null,
    created_at timestamptz not null default now(),

    unique (reference_date)
);


create table if not exists public.mart_revenue_yearly (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,

    faturamento numeric(18, 2) not null default 0,
    pedidos integer not null default 0,
    meses_com_movimento integer not null default 0,

    ticket_medio numeric(18, 2) not null default 0,
    media_mensal numeric(18, 2) not null default 0,

    melhor_mes integer,
    melhor_mes_nome text,
    melhor_mes_faturamento numeric(18, 2),

    pior_mes integer,
    pior_mes_nome text,
    pior_mes_faturamento numeric(18, 2),

    ano_completo boolean not null default false,
    faturamento_ano_anterior numeric(18, 2),
    ano_anterior_completo boolean,
    crescimento_anual numeric(18, 6),

    created_at timestamptz not null default now(),

    unique (reference_date, ano)
);


create table if not exists public.mart_revenue_ytd (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano integer not null,
    mes_limite integer not null,

    faturamento_ytd numeric(18, 2) not null default 0,
    pedidos_ytd integer not null default 0,

    faturamento_ytd_ano_anterior numeric(18, 2),
    crescimento_ytd numeric(18, 6),

    created_at timestamptz not null default now(),

    unique (reference_date, ano, mes_limite)
);


create table if not exists public.mart_revenue_projection_monthly (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano_base integer not null,
    ano_projetado integer not null,

    mes integer not null,
    mes_nome text not null,

    cenario_percentual numeric(10, 6) not null,

    faturamento_base numeric(18, 2) not null default 0,
    participacao_ano_base numeric(18, 6) not null default 0,

    faturamento_projetado numeric(18, 2) not null default 0,
    crescimento_valor numeric(18, 2) not null default 0,

    created_at timestamptz not null default now(),

    unique (
        reference_date,
        ano_base,
        ano_projetado,
        mes,
        cenario_percentual
    )
);


create table if not exists public.mart_revenue_projection_summary (
    id bigint generated by default as identity primary key,
    reference_date date not null,

    ano_base integer not null,
    ano_projetado integer not null,

    cenario_percentual numeric(10, 6) not null,

    faturamento_ano_base numeric(18, 2) not null default 0,
    faturamento_projetado numeric(18, 2) not null default 0,
    crescimento_valor numeric(18, 2) not null default 0,
    media_mensal_projetada numeric(18, 2) not null default 0,

    created_at timestamptz not null default now(),

    unique (
        reference_date,
        ano_base,
        ano_projetado,
        cenario_percentual
    )
);


create index if not exists idx_revenue_monthly_reference
    on public.mart_revenue_monthly (
        reference_date,
        ano,
        mes
    );

create index if not exists idx_revenue_company_reference
    on public.mart_revenue_company_monthly (
        reference_date,
        empresa,
        ano,
        mes
    );

create index if not exists idx_revenue_seller_reference
    on public.mart_revenue_seller_monthly (
        reference_date,
        empresa,
        ano,
        mes
    );

create index if not exists idx_revenue_projection_reference
    on public.mart_revenue_projection_monthly (
        reference_date,
        ano_projetado,
        cenario_percentual
    );