-- ============================================================
-- ARGUS - Revenue Intelligence
-- Annual Forecast
-- ============================================================
--
-- Forecast do fechamento do ano corrente utilizando o
-- run-rate dos meses integralmente encerrados.
--
-- O mês corrente participa do realizado, mas não da base
-- utilizada para calcular a média mensal do forecast.
-- ============================================================

create table if not exists public.mart_revenue_annual_forecast (
    id bigint generated by default as identity primary key,

    reference_date date not null,

    ano integer not null,
    ultimo_mes_fechado integer not null,
    meses_fechados integer not null,

    faturamento_fechado numeric(18, 2) not null default 0,
    faturamento_mes_aberto numeric(18, 2) not null default 0,
    faturamento_realizado numeric(18, 2) not null default 0,

    media_mensal_fechada numeric(18, 2) not null default 0,

    forecast_anual numeric(18, 2) not null default 0,
    restante_estimado numeric(18, 2) not null default 0,

    faturamento_ano_anterior numeric(18, 2),
    crescimento_projetado numeric(18, 6),

    metodo text not null,

    created_at timestamptz not null default now(),

    unique (
        reference_date,
        ano
    )
);


create index if not exists idx_revenue_annual_forecast_reference
    on public.mart_revenue_annual_forecast (
        reference_date,
        ano
    );
